### PR TITLE
Adds the new api client

### PR DESCRIPTION
**Pull request by JohNan**
Fixes issues https://github.com/JohNan/homeassistant-wellbeing/issues/99, https://github.com/JohNan/homeassistant-wellbeing/issues/98, https://github.com/JohNan/homeassistant-wellbeing/issues/93

### CODE REVIEW

**Comment by modo1302** [comment]
hello, @JohNan, not sure if this is just for me, but ufter updating to 1.2.1 I'm getting 500 error while trying to add the integration:
image

**Comment by ElectricWeasel** [comment]
I have a trouble to login into Developer Portal using valid app credentials, getting 500 error. I sent email to Electrolux support, waiting for reply. Maybe related.
Regards
Rafał

**Comment by ElectricWeasel** [comment]
I had to clean mobile app data, relogin, accept T&C then account is available. Trying to use created key/tokens to connect integration.

**Comment by ElectricWeasel** [comment]
Yet i noticed strange behaviour. I can control only Fan On/Off. Moreover trying to set ON give me an message
`Failed to perform the action fan/turn_on. 406, message='Not Acceptable', url=URL('https://api.developer.electrolux.one/api/v1/appliances/950011383129002725087076/command')`
But eventualy fan is ON. I can set OFF without an issue.
Also Ionizer, Safety Lock, UI Light are show but not available.
My device is Pure A9 (PA91-404GY)

Regards
Rafał

**Pull request merged**
