### PR TITLE
Added AEG PX7 Purifier

### PR DESCRIPTION
**Pull request by MickLesk**

### CODE REVIEW

**Comment by JohNan** [comment]
Thank you! I'm not able to verify that it work, so I'll merge it and wait for feedback.

**Comment by MickLesk** [comment]
Works for me :)

**Comment by mountainbikert** [comment]
I'm really trying to get this to work but I'm not succeeding. My AX7 is showing up in the AEG and Electrolux app on my phone. I can manage it from there so all good.
I have installed the integration from HACS, restarted HA, added it through the normal integration screen and used the same credentials there as I use in the apps on my phone.
It keeps saying I have no entities/devices and that setup has failed and it will try again (and fail).

Did I miss a step?

**Comment by MickLesk** [comment]
> I'm really trying to get this to work but I'm not succeeding. My AX7 is showing up in the AEG and Electrolux app on my phone. I can manage it from there so all good.
> I have installed the integration from HACS, restarted HA, added it through the normal integration screen and used the same credentials there as I use in the apps on my phone.
> It keeps saying I have no entities/devices and that setup has failed and it will try again (and fail).
> 
> Did I miss a step?


I deleted the integration in HACS, then adjusted and reloaded it first. With this it worked.

Do you have the latest version? 
Just tried it with another AEG (have 3), also went without problems.

**Comment by mountainbikert** [comment]
Hey @MickLesk , thanks for responding.  So here's what I just did:
- deleted integration in HA
- deleted integration from HACS.
- full shutdown and restart of the system
- installed it again from HACS (made sure it was version 1.0.7)
- restarted HA
- added the integration in HA
- waited
- added my credentials (my email in the username field) and (password in the password field)
- error when trying to setup the integration, will try later it keeps saying.

**Comment by mountainbikert** [comment]
some more info:

Logger: homeassistant.config_entries
Source: config_entries.py:432
First occurred: 21:54:54 (1 occurrences)
Last logged: 21:54:54

Config entry 'email@adress.com' for wellbeing integration not ready yet; Retrying in background

**Comment by STemplar** [comment]
afbeelding
Should we add the AX5 and AX9 models too?

**Comment by MickLesk** [comment]
> afbeelding
> Should we add the AX5 and AX9 models too?


I can do this tomorrow, you can Test this, because i dont have AX5 / AX9 😅

**Comment by MickLesk** [comment]
@STemplar ive added AX5 & AX9

**Pull request merged**
