### PR TITLE
Support for 700 series Robot Vacuum

### PR DESCRIPTION
**Pull request by ivancoppa**
I have added basic support for the 700 Series Robot Vacuum, the successor to the PUREi9 Series, which differs from the PUREi9 in terms of capabilities.

In this version, support for the 700 Series Vacuum Mode (also known as Power Mode in PUREi9) is not yet included, as I am still determining the best approach to implement this feature.

However, this basic implementation should allow users to set up essential automations.

This implementation provides basic vacuum support for the following models:

**Electrolux**
- Clean 600
- Hygienic 600
- Hygienic 700
- Ultimate 700

**AEG**
- 6000 Robot Vacuum Cleaner
- 7000 Robot Vacuum Cleaner

### CODE REVIEW

**Review by JohNan — APPROVED** [review]
Thank you! It looks great! Well done.

**Comment by ivancoppa** [comment]
Thank you!

It would be greatly appreciated if @joakimjalden and @derkrasseleo could also verify that this update doesn’t cause any regressions with the PUREi9 and PUREi9.2 models.

**Comment by joakimjalden** [comment]
> It would be greatly appreciated if @joakimjalden and @derkrasseleo could also verify that this update doesn’t cause any regressions with the PUREi9 and PUREi9.2 models.

@ivancoppa  Functionally it works (start, pause, stop, return) but the addition messes up the battery status. The battery status of the PUREi9 is reported as an integer number in the range of 1 to 6, not a percentage. The change makes the integration report a full battery on the PUREi9.2 as only 6% full. I have not had time to debug in my development environment (and will not be able to for a few days) but I would assume that something goes wrong with the `battery_range` property on line 398 in `api.py`.

**Comment by joakimjalden** [comment]
...and out of curiosity, do the newer models report any capabilities for maps and cleaning zones?

**Comment by derkrasseleo** [comment]
Can confirm, battery status shows 6% for me, even though the robot was charging all day..

**Comment by joakimjalden** [comment]
@ivancoppa Also, a suggestion is to change line 56 in `vacuum.py` to `VACUUM_CHARGING_STATES = [9, 'sleeping']` or `VACUUM_CHARGING_STATES = [9, 'idle']` and then line 114 to `charging = self.get_entity.state in VACUUM_CHARGING_STATES` so that the new models also get the little lightning bolt by the battery when charging.

**Comment by ivancoppa** [comment]
@derkrasseleo @joakimjalden, thanks so much for checking!
I hope to work on a fix tomorrow and implement your suggestions.

> ...and out of curiosity, do the newer models report any capabilities for maps and cleaning zones? Could you post the "capabilities" part of the reply to the appliance info call?

From what I observed, it doesn’t seem to support cleaning zones, it just draws the map in the app.

**Comment by joakimjalden** [comment]
@ivancoppa I was mucking about in the code today, and I have another suggestion for the 700 series support. When implementing the PUREi9 support, I got the (good) suggestion to give the Vacuum Entity a default friendly name based on the appliance name; see

https://github.com/JohNan/homeassistant-wellbeing/pull/146#issue-2554857654

I'm assuming the change would be a simple change of line [223](https://github.com/JohNan/homeassistant-wellbeing/blob/dc3a4401af294feefa98cc3c149a46286f4ccf49/custom_components/wellbeing/api.py#L223) in ´api.py` to [206](https://github.com/JohNan/homeassistant-wellbeing/blob/dc3a4401af294feefa98cc3c149a46286f4ccf49/custom_components/wellbeing/api.py#L206). Maybe we should also consolidate the naming convention (now "Vacuum" for PUREi9 and "Robot Status" for the 700 series).

**Comment by ivancoppa** [comment]
Good point @joakimjalden,
I'll try to have a look during the weekend.

**Comment by joakimjalden** [comment]
Hi @ivancoppa 

> > ...and out of curiosity, do the newer models report any capabilities for maps and cleaning zones? Could you post the "capabilities" part of the reply to the appliance info call?
> 
> From what I observed, it doesn’t seem to support cleaning zones, it just draws the map in the app.

The Pure i9 now reports back zones and additional commands, see https://developer.electrolux.one/news :D

**Pull request merged**
